== Examples

These examples do not draw on any currently defined objectclass but are intended to indicate some uses.
Properties used here may not be defined in any specification.

=== Eduperson vcard

The eduperson ldap objectclass provides for a number of attributes considered useful for interaction between
members of educational organizations. A corresponding vcard objectclass would allow for better mappping of
ldap directories onto a vcard representation.

The 201203 specification of the LDAP objectclass for reference. Note that all attributes are `MAY` so would
have a vcard cardinality of *1 or *.

[source%unnumbered]
----
( 1.3.6.1.4.1.5923.1.1.2
  NAME 'eduPerson'
    AUXILIARY
    MAY ( eduPersonAffiliation $
        eduPersonNickname $
        eduPersonOrgDN $
        eduPersonOrgUnitDN $
        eduPersonPrimaryAffiliation $
        eduPersonPrincipalName $
        eduPersonEntitlement $
        eduPersonPrimaryOrgUnitDN $
        eduPersonScopedAffiliation $
        eduPersonTargetedID $
        eduPersonAssurance)
----

A vcard mapping would, where possible use existing vcard properties. Where not possible new properties
could be defined.

[source%unnumbered]
----
BEGIN:VCARD
VERSION:4.0
UID:urn:uuid:4fbe8971-0bc3-424c-9c26-36c3e1eff6b1
FN:J. Doe
N:Doe;J.;;;
EMAIL:jdoe@example.edu
TEL;VALUE=uri:tel:+1-555-555-5555
OBJECTCLASS:eduperson
NICKNAME:Jack
ORGDN: dc=example, dc=edu
AFFILIATION;TYPE=primary:faculty
AFFILIATION;TYPE=scoped:faculty@cs.example.edu
END:VCARD
----

=== Schedulable

A schedulable entity can be scheduled for meetings (as a person) or for use (as a resource). For a
scheduling system to be able to usefully manage the schedule it needs specific information.

At the very least there needs to be some form of calendar user address. It's useful to know whether requests
can be auto accepted if the slot is available.

Building on the previous example we'll make Jack schedulable.

[source%unnumbered]
----
BEGIN:VCARD
VERSION:4.0
UID:urn:uuid:4fbe8971-0bc3-424c-9c26-36c3e1eff6b1
FN:J. Doe
N:Doe;J.;;;
EMAIL:jdoe@example.edu
TEL;VALUE=uri:tel:+1-555-555-5555
OBJECTCLASS:eduperson
NICKNAME:Jack
ORGDN: dc=example, dc=edu
AFFILIATION;TYPE=primary:faculty
AFFILIATION;TYPE=scoped:faculty@cs.example.edu
OBJECTCLASS:schedulable
CALADRURI:jdoe@example.edu
AUTOSCHEDULE:ACCEPT-IF-FREE
END:VCARD
----
